package Hospital;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.table.DefaultTableModel;

import com.mysql.cj.jdbc.result.ResultSetMetaData;

import javax.swing.ListSelectionModel;
import javax.swing.plaf.OptionPaneUI;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author alokt
 */
public class show_doc extends javax.swing.JFrame {

    /**
	 * 
	 */
	/**
     * Creates new form show
     */
    public show_doc() {
        initComponents();
        this.setLocationRelativeTo(null);
        upDateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">    
    int q,i,deleteItem;
	String id;
    
    public void upDateDB()
    {
    	try {
    		conn cc=new conn();
    		String query1="SELECT * FROM doctor";
    		ResultSet rs=cc.st.executeQuery(query1);
    		ResultSetMetaData stData= (ResultSetMetaData) rs.getMetaData();
    		q=stData.getColumnCount();
    		
    		DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
    		RecordTable.setRowCount(0);
    		
    		while(rs.next())
    		{
    			Vector columnData=new Vector();
    			
    			for (i=1;i<=q;i++)
    			{
    				columnData.add(rs.getString("doctor_id"));
    				columnData.add(rs.getString("name"));
    				columnData.add(rs.getString("qualification"));
    				columnData.add(rs.getString("specialization"));
    				columnData.add(rs.getString("ward"));
    			}
    			RecordTable.addRow(columnData);
    		}
    	
    	}
    	catch (Exception e) {
			// TODO: handle exception
    		JOptionPane.showMessageDialog(null,e);
		}
    		
    }
    public void txtblank()
    {
    	jtxt_doctorid.setText("");
		jtxt_name.setText("");
		jtxt_qualification.setText("");
		jtxt_specialization.setText("");
		jtxt_ward.setText("");
    }
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbl_doctorid = new javax.swing.JLabel();
        jtxt_doctorid = new javax.swing.JTextField();
        jtxt_name = new javax.swing.JTextField();
        jlbl_name = new javax.swing.JLabel();
        jlbl_qualification = new javax.swing.JLabel();
        jtxt_qualification = new javax.swing.JTextField();
        jlbl_specilization = new javax.swing.JLabel();
        jtxt_specialization = new javax.swing.JTextField();
        jlbl_ward = new javax.swing.JLabel();
        jtxt_ward = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtn_update = new javax.swing.JButton();
        jbtn_reset = new javax.swing.JButton();
        
        jbtn_add = new javax.swing.JButton();
        jbtn_exit = new javax.swing.JButton();
        jbtn_delete = new javax.swing.JButton();
        
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		
        		DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
        		int Selectedrow=jTable1.getSelectedRow();
        		
        		jtxt_doctorid.setText(RecordTable.getValueAt(Selectedrow,0).toString());
        		jtxt_name.setText(RecordTable.getValueAt(Selectedrow,1).toString());
        		jtxt_qualification.setText(RecordTable.getValueAt(Selectedrow,2).toString());
        		jtxt_specialization.setText(RecordTable.getValueAt(Selectedrow,3).toString());
        		jtxt_ward.setText(RecordTable.getValueAt(Selectedrow,4).toString());
        	}
        });
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 143, 203), 8));
        jPanel1.setPreferredSize(new java.awt.Dimension(1430, 800));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 143, 203), 8));

        jlbl_doctorid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbl_doctorid.setText("DoctorID");

        jtxt_doctorid.setFont(new java.awt.Font("Tahoma", 1, 24));
        
        jtxt_name.setFont(new java.awt.Font("Tahoma", 1, 24));

        jlbl_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbl_name.setText("Name");

        jlbl_qualification.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbl_qualification.setText("Qualification");

        jtxt_qualification.setFont(new java.awt.Font("Tahoma", 1, 24));

        jlbl_specilization.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbl_specilization.setText("Specialization");

        jtxt_specialization.setFont(new java.awt.Font("Tahoma", 1, 24));
        

        jlbl_ward.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbl_ward.setText("Ward Assigned");

        jtxt_ward.setFont(new java.awt.Font("Tahoma", 1, 24));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 143, 203), 8));

        jbtn_update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_update.setText("Update");
        jbtn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_updateActionPerformed(evt);
            }

			
        });

        jbtn_reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_reset.setText("Reset");
        jbtn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_resetActionPerformed(evt);
            }
        });

        jbtn_add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_add.setText("Add");
        jbtn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_addActionPerformed(evt);
            }

			
        });

        jbtn_exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_exit.setText("Exit");
        jbtn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_exitActionPerformed(evt);
            }
        });

        jbtn_delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn_delete.setText("Delete");
        jbtn_delete.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deleteActionPerformed(evt);
            }

			
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_update)
                .addGap(18, 18, 18)
                .addComponent(jbtn_reset)
                .addGap(18, 18, 18)
                .addComponent(jbtn_delete)
                .addGap(18, 18, 18)
                .addComponent(jbtn_exit)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jlbl_doctorid, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlbl_specilization)
        				.addComponent(jlbl_ward)
        				.addComponent(jlbl_name, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlbl_qualification))
        			.addGap(36)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jtxt_specialization, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 608, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jtxt_ward, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 608, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jtxt_doctorid, GroupLayout.PREFERRED_SIZE, 608, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jtxt_name, GroupLayout.PREFERRED_SIZE, 608, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jtxt_qualification, GroupLayout.PREFERRED_SIZE, 608, GroupLayout.PREFERRED_SIZE))
        			.addGap(114)
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(21))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(32)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jlbl_doctorid)
        						.addComponent(jtxt_doctorid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jlbl_name)
        						.addComponent(jtxt_name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jlbl_qualification)
        						.addComponent(jtxt_qualification, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jtxt_specialization, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jlbl_specilization))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jtxt_ward, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jlbl_ward)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Doctors Info");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(525, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(448, 448, 448))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        		{null, null, null, null, null},
        	},
        	new String[] {
        		"Doctor Id", "Name", "Qualification", "Specialization", "Ward Assigned"
        	}
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(20, 159, 91));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1180, GroupLayout.PREFERRED_SIZE)
        			.addGap(121))
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel5.setLayout(jPanel5Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(76)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(jPanel5, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
        						.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
        			.addGap(32))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

   
                                               
    PreparedStatement pst;
    private void jbtn_addActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		try {
			conn cc=new conn();
    		//String query1="SELECT * FROM doctor";
    		//ResultSet rs=cc.st.executeQuery(query1);
    		pst=cc.c.prepareStatement("insert into doctor(doctor_id,name,qualification,specialization,ward)value(?,?,?,?,?)");
    		
    		pst.setString(1,jtxt_doctorid.getText());
    		pst.setString(2,jtxt_name.getText());
    		pst.setString(3,jtxt_qualification.getText());
    		pst.setString(4,jtxt_specialization.getText());
    		pst.setString(5,jtxt_ward.getText());
    		
    		pst.executeUpdate();
    		JOptionPane.showMessageDialog(this,"Record Added");
    		upDateDB();
    		txtblank();
    		
		}
		 
		
		catch (SQLException ex)
		{
			java.util.logging.Logger.getLogger(show_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
	}    
    
    private void jbtn_updateActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	try {
    		conn cc=new conn();
    		pst=cc.c.prepareStatement("update doctor set doctor_id=?,name=?,qualification=?,specialization=?,ward=? where doctor_id=?");
    		DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
    		int Selectedrow=jTable1.getSelectedRow();
    		id=RecordTable.getValueAt(Selectedrow,0).toString();
    		
    		pst.setString(1,jtxt_doctorid.getText());
    		pst.setString(2,jtxt_name.getText());
    		pst.setString(3,jtxt_qualification.getText());
    		pst.setString(4,jtxt_specialization.getText());
    		pst.setString(5,jtxt_ward.getText());
    		pst.setString(6,id);
    		
    		pst.executeUpdate();
    		
    		JOptionPane.showMessageDialog(this, "Record Updated");
    		upDateDB();
    		txtblank();
    		
    	
    	}
    	catch (Exception e) {
			// TODO: handle exception
    		JOptionPane.showMessageDialog(null,e);
		}
		
	}

    private void jbtn_resetActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	jtxt_doctorid.setText("");
    	jtxt_name.setText("");
    	jtxt_qualification.setText("");
    	jtxt_specialization.setText("");
    	jtxt_ward.setText("");
    	
    } 
    
    private void jbtn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
		DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
		int Selectedrow=jTable1.getSelectedRow();
		
		try
		{
			id=RecordTable.getValueAt(Selectedrow,0).toString();
			deleteItem=JOptionPane.showConfirmDialog(this,"Confirm if you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
			
			if(deleteItem==JOptionPane.YES_OPTION)
			{
				conn cc=new conn();
				pst=cc.c.prepareStatement("delete from doctor where doctor_id=?");
			    pst.setString(1,id);
				pst.executeUpdate();
				JOptionPane.showMessageDialog(this,"Record Updated");
				upDateDB();
				txtblank();
				
				
				
			}
		}
		catch (Exception e) {
			// TODO: handle exception
		}
		
	}
    
   
    private JFrame frame;
    private void jbtn_exitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	frame=new JFrame("Exit");
    	if(JOptionPane.showConfirmDialog(frame,"Confirm you want to exit","Doctor Info",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    	{
    		
    		new doctors();
    		show_doc.this.setVisible(false);
    		
    	}
    			
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_doc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_doc().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jbtn_update;
    private javax.swing.JButton jbtn_reset;
    private javax.swing.JButton jbtn_add;
    private javax.swing.JButton jbtn_exit;
    private javax.swing.JButton jbtn_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbl_doctorid;
    private javax.swing.JLabel jlbl_name;
    private javax.swing.JLabel jlbl_qualification;
    private javax.swing.JLabel jlbl_specilization;
    private javax.swing.JLabel jlbl_ward;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxt_doctorid;
    private javax.swing.JTextField jtxt_name;
    private javax.swing.JTextField jtxt_qualification;
    private javax.swing.JTextField jtxt_specialization;
    private javax.swing.JTextField jtxt_ward;
    // End of variables declaration                   
}
